### Generated by rprotoc. DO NOT EDIT!
### <proto file: thumbTask.proto>
# package floorplanner;
# 
# message ThumbTask {
# 
#     enum AssetType {
#         DAE = 0;
#         SWF = 1;
#     }
# 
#     required string resultPath = 1;
#     required AssetType type = 2;
#     required bytes asset = 3;
#     repeated ThumbStyle styles = 4;
# }
# 
# message ThumbStyle {
#     required string name = 1;
#     required int32 size = 2;
# }

require 'protobuf/message/message'
require 'protobuf/message/enum'
require 'protobuf/message/service'
require 'protobuf/message/extend'

module Floorplanner
  class ThumbTask < ::Protobuf::Message
    defined_in __FILE__
    class AssetType < ::Protobuf::Enum
      defined_in __FILE__
      DAE = value(:DAE, 0)
      SWF = value(:SWF, 1)
    end
    required :string, :resultPath, 1
    required :AssetType, :type, 2
    required :bytes, :asset, 3
    repeated :ThumbStyle, :styles, 4

    include Celerb::Task
    task_name 'thumbs.tasks.thumb3D'

    def to_celery
      serialize_to_string
    end
  end
  class ThumbStyle < ::Protobuf::Message
    defined_in __FILE__
    required :string, :name, 1
    required :int32, :size, 2
  end
end
